version: 2

jobs:
  test:
    docker:
      - image: node:10
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run:
          environment:
            JEST_JUNIT_OUTPUT: reports/junit/js-test-results.xml
          command: npm test -- --ci --coverage --maxWorkers=2
      - run: npx codecov
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - store_artifacts:
          path: coverage

  docs:
    docker:
      - image: node:10
    steps:
      - checkout
      - run: npm ci
      - run: npm run docs

workflows:
  version: 2
  test-docs:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - gh-pages
      - docs:
          requires:
            - test
          filters:
            branches:
              only:
                - master
